# Generated by Django 4.2.11 on 2024-08-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_method",
            field=models.CharField(
                choices=[
                    ("Branch", "Branch"),
                    ("Courier", "Courier"),
                    ("Parcel Locker", "Parcel Locker"),
                ],
                max_length=48,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="email",
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="first_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="last_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("Card", "Card"), ("Upon Receipt", "Upon Receipt")],
                default=0,
                max_length=48,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="surname",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
