# Generated by Django 4.2.11 on 2024-09-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "delivery",
            "0002_order_delivery_method_order_email_order_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_method",
            field=models.CharField(
                choices=[
                    ("Branch", "Branch"),
                    ("Courier", "Courier"),
                    ("Parcel Locker", "Parcel Locker"),
                ],
                max_length=48,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="surname",
            field=models.CharField(max_length=100),
        ),
    ]
