# Generated by Django 4.2.11 on 2024-09-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0003_alter_order_city_alter_order_delivery_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="branch",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
