# Generated by Django 4.2.11 on 2024-09-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0005_order_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processing", "Processing"),
                    ("Shipped", "Shipped"),
                    ("Waiting_for_payment", "Waiting_for_payment"),
                    ("Payment_Ok", "Payment_Ok"),
                    ("Completed", "Completed"),
                    ("Canceled", "Canceled"),
                ],
                max_length=20,
            ),
        ),
    ]
