# Generated by Django 4.2.11 on 2024-10-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0006_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="street",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
