version: '3.12'


services:
  api:
    container_name: api
    build:
      context: .
      target: base
      args:
        DJANGO_ENV: development
    command: [ "python", "-Wd", "./src/manage.py", "runserver", "0.0.0.0:${SERVER_PORT}" ]
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    volumes:
      - "./:/usr/app"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      db:
        condition: service_healthy

  test:
    container_name: test_runner
    build:
      context: .
      target: base
      args:
        DJANGO_ENV: test
    command: [ "pytest", "--cov", "." ]
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    volumes:
      - "./:/usr/app"
    working_dir: /usr/app/src
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy



  db:
    image: postgres:16.2
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 3

  db-initializer:
    container_name: db_initializer
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      ALLOWED_HOSTS: "*"
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DJANGO_SETTINGS_MODULE: config.settings
    volumes:
      - "./:/usr/app"
    command: [ "python", "./src/manage.py", "migrate" ]


volumes:
  postgres_data:
