# Generated by Django 4.2.11 on 2024-06-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="sizes",
            field=models.IntegerField(),
        ),
    ]
