# Generated by Django 4.2.11 on 2024-05-14 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcategory",
            name="description",
        ),
    ]
