# Generated by Django 4.2.11 on 2024-06-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_category_slug_alter_product_sizes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
        migrations.AlterField(
            model_name="product",
            name="sizes",
            field=models.TextField(),
        ),
    ]
