# Generated by Django 4.2.11 on 2024-06-10 17:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_remove_category_slug_alter_product_sizes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="colors",
            new_name="color",
        ),
    ]
