# Generated by Django 4.2.11 on 2024-06-10 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_rename_colors_product_color"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="sizes",
            new_name="size",
        ),
    ]
