# Generated by Django 4.2.11 on 2024-06-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_gender_remove_category_name_category_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="gender",
            field=models.CharField(
                choices=[(1, "Male"), (2, "Female")], default=1, max_length=15
            ),
        ),
        migrations.DeleteModel(
            name="Gender",
        ),
    ]
