# Generated by Django 4.2.11 on 2024-06-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_alter_category_gender_delete_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AddField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=15,
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
