# Generated by Django 4.2.11 on 2024-06-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_remove_size_size_product_category_size_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Кросівки", "Кросівки"),
                    ("Футболки", "Футболки"),
                    ("Шорти", "Шорти"),
                    ("Штани", "Штани"),
                    ("Світшоти", "Світшоти"),
                ],
                default="Футболки",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.CharField(
                choices=[
                    ("Чорний", "Чорний"),
                    ("Білий", "Білий"),
                    ("Синій", "Синій"),
                    ("Різнокольорові", "Різнокольорові"),
                ],
                default="Білий",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.CharField(
                choices=[
                    ("36", "36"),
                    ("37", "37"),
                    ("38", "38"),
                    ("39", "39"),
                    ("40", "40"),
                    ("41", "41"),
                    ("42", "42"),
                    ("43", "43"),
                    ("44", "44"),
                    ("45", "45"),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("XXL", "XXL"),
                ],
                max_length=15,
            ),
        ),
        migrations.DeleteModel(
            name="Size",
        ),
    ]
