# Generated by Django 4.2.11 on 2024-06-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_alter_product_category_alter_product_color_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_urls", models.ImageField(upload_to="")),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="image_urls",
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Кросівки", "Кросівки"),
                    ("Футболки", "Футболки"),
                    ("Шорти", "Шорти"),
                    ("Штани", "Штани"),
                    ("Світшоти", "Світшоти"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.CharField(
                choices=[
                    ("Чорний", "Чорний"),
                    ("Білий", "Білий"),
                    ("Синій", "Синій"),
                    ("Різнокольорові", "Різнокольорові"),
                ],
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ManyToManyField(related_name="products", to="products.image"),
        ),
    ]
