# Generated by Django 4.2.11 on 2024-06-18 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_productimage_remove_product_image_delete_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("picture", models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
        migrations.AddField(
            model_name="product",
            name="image_urls",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.image",
            ),
        ),
    ]
