# Generated by Django 4.2.11 on 2024-06-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0017_productimage_remove_product_image_urls_delete_image_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("picture", models.ImageField(upload_to="")),
            ],
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="product_img", to="products.picture"
            ),
        ),
    ]
