# Generated by Django 4.2.11 on 2024-08-13 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0001_initial"),
        ("products", "0023_productcolor_delete_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouseitem",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wh_items",
                to="delivery.order",
            ),
        ),
    ]
