# Generated by Django 4.2.11 on 2024-08-02 06:18

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_alter_basket_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basket",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
