# Generated by Django 4.2.11 on 2024-08-13 07:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0006_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
