# Generated by Django 4.2.11 on 2024-05-21 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_delete_passwordreset"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordReset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("token", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                max_length=128,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\w+$",
                        "Name can only contain letters and must be at least 1 characters long ",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                max_length=128,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\w+$", "Last name can only contain letters"
                    ),
                    django.core.validators.MinLengthValidator(
                        1, "Last name must be at least 1 characters long"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="surname",
            field=models.CharField(
                max_length=128,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\w+$", "Surname can only contain letters"
                    ),
                    django.core.validators.MinLengthValidator(
                        1, "Surname must be at least 1 characters long"
                    ),
                ],
            ),
        ),
    ]
