# Generated by Django 4.2.11 on 2024-05-21 17:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_passwordreset_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PasswordReset",
        ),
    ]
