name: Check code quality

on:
  - pull_request

jobs:
  code-qality:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Setup Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install Poetry and dependencies
      - name: Install poetry
        run: |
          pip install poetry
          poetry install

      # Run code formatters
      - name: Run formatters
        run: |
          poetry run black --check .
          poetry run isort --check . --profile black

      # Run tests
      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: config.settings
          PYTHONPATH: ./src
        run: |
          poetry run pytest --cov=src --cov-report=xml
