name: Check code quality

on:
  pull_request:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install poetry
        run: pip install poetry && poetry install
      - name: Run formatters
        run: poetry run black --check . && poetry run isort --check . --profile black

  test:
    runs-on: ubuntu-latest
    needs: code-quality  # Этот шаг зависит от выполнения job'ы code-quality
    steps:
      - uses: actions/checkout@v4

      - name: Set up gcloud credentials
        run: |
          echo "${{ secrets.GCLOUD_SECRET }}" > gcloud-secret.json
        env:
          GCLOUD_SECRET: ${{ secrets.GCLOUD_SECRET }}

      - name: Set DJANGO_SETTINGS_MODULE to test settings
        run: echo "DJANGO_SETTINGS_MODULE=src.config.settings_test" >> $GITHUB_ENV

      - name: Install poetry dependencies
        run: pip install poetry && poetry install

      - name: Change to src directory
        run: cd src  # Переходим в директорию src

      - name: Run tests
        run: |
          pytest --settings=config.settings_test
