name: Check code quality

on:
  pull_request:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install poetry
        run: pip install poetry && poetry install
      - name: Run formatters
        run: poetry run black --check . && poetry run isort --check . --profile black

  test:
    runs-on: ubuntu-latest
    needs: code-quality  
    steps:
      - uses: actions/checkout@v4

      - name: Set up gcloud credentials
        run: |
          echo "${{ secrets.GCLOUD_SECRET_BASE64 }}" | base64 --decode > /tmp/gcloud-secret.json
      
      - name: Install poetry dependencies
        run: pip install poetry && poetry install

      - name: Install pytest
        run: |
          poetry add --dev pytest 
      
      - name: Set DJANGO_SETTINGS_MODULE to test settings
        run: echo "DJANGO_SETTINGS_MODULE=config.settings_test" >> $GITHUB_ENV

      - name: Run tests
        run: |
          export GCLOUD_CREDENTIALS_PATH=/tmp/gcloud-secret.json
          poetry run pytest src


