name: Check code quality

on:
  - pull_request

jobs:
  code-qality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install poetry
        run: pip install poetry && poetry install
      - name: Run formatters
        run: poetry run black --check . && poetry run isort --check . --profile black

  tests:
      runs-on: ubuntu-latest
      steps:
        # 1. Клонирование репозитория
        - name: Checkout code
          uses: actions/checkout@v4

        # 2. Установка Docker
        - name: Set up Docker
          uses: docker/setup-buildx-action@v2

        # 3. Построение и запуск тестов
        - name: Run tests
          run: |
            docker-compose up tests --abort-on-container-exit     
