name: Check code quality

on:
  - pull_request

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install poetry && poetry install

      - name: Create gcloud-secret.json in the container
        env:
          GCLOUD_SECRET: ${{ secrets.GCLOUD_SECRET }}
        run: |
          echo "${GCLOUD_SECRET}" > gcloud-secret.json
          docker cp gcloud-secret.json api:/usr/app/gcloud-secret.json

      - name: Run formatters
        run: poetry run black --check . && poetry run isort --check . --profile black

      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: config.settings
          PYTHONPATH: ./src
          GOOGLE_APPLICATION_CREDENTIALS: /usr/app/gcloud-secret.json
        run: poetry run pytest --cov=src --cov-report=xml



