name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.16
        options: --privileged

    steps:
      # 1. Клонируем репозиторий
      - uses: actions/checkout@v4

      # 2. Настроим Docker Compose
      - name: Set up Docker Compose
        run: |
          curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      # 3. Строим и запускаем контейнеры с использованием Docker Compose
      - name: Build and start test container
        run: |
          docker-compose -f docker-compose.yml up --build -d test  # Запуск контейнера для тестов

      # 4. Выполнение тестов в контейнере
      - name: Run tests inside the test container
        run: |
          docker exec -it test_runner poetry run pytest --cov=src --cov-report=xml

      # 5. Останавливаем контейнеры после выполнения тестов
      - name: Stop containers
        run: |
          docker-compose down





